"""Training starter for a lightweight wake-word detector using PyTorch.

This is a minimal training loop that expects features generated by
`tools/generate_spectrograms.py` in `features/*.npz`.

Requirements: torch, torchvision, numpy

Usage (example):
    python tools/train_wake.py --features features --epochs 20 --batch 32

This script is intentionally small and educational — fine-tune model
and hyperparameters for production.
"""
import argparse
from pathlib import Path
import numpy as np

try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    from torch.utils.data import Dataset, DataLoader
except Exception:
    torch = None

class FeatureDataset(Dataset):
    def __init__(self, folder):
        files = list(Path(folder).glob('*.npz'))
        self.samples = files
    def __len__(self):
        return len(self.samples)
    def __getitem__(self, idx):
        data = np.load(self.samples[idx])
        mel = data['mel']
        label = data['label'].astype(np.int64)
        # Add channel dimension
        mel = mel[np.newaxis, ...]
        return torch.tensor(mel, dtype=torch.float32), torch.tensor(label, dtype=torch.long)

class TinyCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(1, 8, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(8, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )
        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(16 * 16 * 16, 64),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(64, 2)
        )
    def forward(self, x):
        x = self.conv(x)
        x = self.fc(x)
        return x

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--features', type=str, default='features')
    parser.add_argument('--epochs', type=int, default=10)
    parser.add_argument('--batch', type=int, default=16)
    args = parser.parse_args()

    if torch is None:
        print('PyTorch not installed. Install torch to train: pip install torch')
        raise SystemExit(1)

    dataset = FeatureDataset(args.features)
    if len(dataset) == 0:
        print('No feature files found. Run tools/generate_spectrograms.py first.')
        raise SystemExit(1)

    loader = DataLoader(dataset, batch_size=args.batch, shuffle=True)
    model = TinyCNN()
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model.to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    for epoch in range(args.epochs):
        model.train()
        total = 0
        correct = 0
        for x, y in loader:
            x = x.to(device)
            y = y.to(device)
            optimizer.zero_grad()
            out = model(x)
            loss = criterion(out, y)
            loss.backward()
            optimizer.step()
            preds = out.argmax(dim=1)
            total += y.size(0)
            correct += (preds == y).sum().item()
        acc = correct / total if total>0 else 0
        print(f'Epoch {epoch+1}/{args.epochs} - acc={acc:.3f}')

    # Save model
    torch.save(model.state_dict(), 'wake_model.pt')
    print('Saved wake_model.pt')
